### PR TITLE
fix: changed workspace to version-14

### LINKED ISSUE #85: Wiki Workspace is outdated and not displayed
Hello, the wiki workspace defined in the wiki app files is outdated, because it does not contain any list defined in json (which are required for workspaces in  recent Frappe releases), resulting in a bugged workspace which is not displayed to the user.

The associated error is the following : "required content data of type list".

### PR DESCRIPTION
**Pull request by nikkothari22**
Updated the Workspace to version 14

image

Closes #85

### CODE REVIEW

**Comment by shariquerik** [comment]
For frappe version 13 it will break

**Comment by nikkothari22** [comment]
> For frappe version 13 it will break

We don't have a separate branch for version-13 and version-14 like Frappe? 

Last I checked, Wiki didn't work well on version-13. I assumed it only supports v14.

**Comment by ankush** [comment]
@nikkothari22 we do I guess https://github.com/frappe/wiki/tree/version-13

**Comment by itanand** [comment]
I have Also checked , WiKi didnot work well with Version 13.

**Review by BreadGenie — APPROVED** [review]
Thanks for raising the PR

**Pull request merged**
