### PR TITLE
feat: add support for tiptap task-item

### LINKED ISSUE #177: Are task lists within the scope of this project?
Tiptap supports it via the [task-list extension](https://tiptap.dev/api/nodes/task-list)

Trying to mimic Github task lists for my use case
- [x] Pending task 1
- [ ] Pending task 2

### PR DESCRIPTION
**Pull request by Zyten**
Fixes #177

### CODE REVIEW

**Review by BreadGenie — CHANGES_REQUESTED** [review]
Thanks for the PR!
Noticed a bug where the state of the task item isn't shown correctly in edit mode.
eg: If I save with one task item checked and after a while, If I'm editing it, it will show as unchecked.

### View Mode
image

### Edit Mode
image

**Comment by Zyten** [comment]
That glitch seems to be due to this line:
```js
const content = `<div markdown="1">${$(".editor-space .ProseMirror")
  .html()
  .replace(/<h1>.*?<\/h1>/, "")}</div>`;
```

Sample output:
```js
<ul data-type="taskList">
  <li data-checked="true">
    <label contenteditable="false">
      <input type="checkbox" checked="checked">
      <span></span>
    </label>
    <div>
      <p>Task 1</p>
      <p>Description</p>
    </div>
  </li>
</ul>
```

Fixed when updated like so:
```js
const content = `<div markdown="1">${editor.getHTML()
  .replace(/<h1>.*?<\/h1>/, "")}</div>`;
```

Sample output:
```js
<ul data-type="taskList">
  <li data-checked="true" data-type="taskItem">
    <label>
      <input type="checkbox" checked="checked">
      <span></span>
    </label>
    <div>
      <p>Task 1</p>
      <p>Description</p>
    </div>
  </li>
</ul>
```


But it seems like changing it would introduce regression to existing code though. The issue mentioned there is still open (ueberdosis/tiptap#4044)

**Comment by Zyten** [comment]
On a related note,

It seems like task-item state is only saved in Edit mode but it's still editable in View mode.

I think the optimal solution would be to allow saving state for it regardless of whether or not the editor is in editable mode  (same as Github) but there seems to be a known bug for this option (ueberdosis/tiptap#3676) that hasn't been resolved.

Alternatively I think having the checkbox be read only when in View mode would also be acceptable - as it should already be with the default settings but that does not work as expected (I believe it's due to the same bug). So I added a temporary manual override instead.

**Comment by Zyten** [comment]
No worries :)

If that's the case, I'll update the code such that the jquery method is retained and see if I can fix it using an alternative method. I suspect I just need to append `data-type="taskItem"` to the list item prior to saving.

As for the other issue, since not using tiptap view mode is a design decision, would it be okay to keep my manual patch to make the checkbox readonly when in Wiki's View Mode? I added comments to remove the patch once the upstream bug is fixed.

**Comment by BreadGenie** [comment]
> As for the other issue, since not using tiptap view mode is a design decision, would it be okay to keep my manual patch to make the checkbox readonly when in Wiki's View Mode? I added comments to remove the patch once the upstream bug is fixed.

Works for me

**Pull request merged**
