### PR TITLE
wip: Wiki On Steroids

### PR DESCRIPTION
**Pull request by hasnain2808**
1. Approval Mechanism
2. Migrate from www/
3. build.json --> ESbuild 
4. breadcrumbs on show
5. Wiki Sidebar (Converted Web Sidebar to tree)
6. Hierarchial Sidebar
7. docs search URL taken from the sidebars
8. Attachments support in edit mode from portal too
9. Rich Text Editor Support with attachment support
10. Collapsible headers in sidebar
11. Drag and drop support for sidebar in edit mode
12. Custom script support in wiki settings
13. Cached sidebar context
14. Auto table of contents highlighting
15. Two way communication between reviewer and patch raiser

### CODE REVIEW

**Comment by federicocalvo** [comment]
Hi @hasnain2808, I tried the PR branch twice but for some reason I can't see the published web view of the wiki. In the master branch I can.
Any recommendations as to what I might be doing wrong? I am very interested in the additions you are making.
Thanks!

**Comment by hasnain2808** [comment]
> Hi @hasnain2808, I tried the PR branch twice but for some reason I can't see the published web view of the wiki. In the master branch I can.
> Any recommendations as to what I might be doing wrong? I am very interested in the additions you are making.
> Thanks!

@federicocalvo 
Can you share some screenshots or tracebacks of what issues you're facing?

**Comment by federicocalvo** [comment]
Yes.

When i press **See on Web Site** that de traceback:

Captura de Pantalla 2021-06-14 a la(s) 13 12 43


```Traceback (most recent call last):
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/diamo/Frappe/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 1, in top-level template code
    {% extends "wiki/doctype/wiki_page/templates/wiki_doc.html" %}
  File "/home/diamo/Frappe/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 2, in top-level template code
    {%- from "templates/includes/navbar/navbar_items.html" import render_item -%}
  File "/home/diamo/Frappe/apps/frappe/frappe/./templates/base.html", line 41, in top-level template code
    {%- block head_include %}
  File "/home/diamo/Frappe/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 9, in block "head_include"
    {{ include_style('wiki.bundle.css') }}
  File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'include_style' is undefined```

**Comment by hasnain2808** [comment]
> Yes.
> 
> When i press **See on Web Site** that de traceback:
> 
> Captura de Pantalla 2021-06-14 a la(s) 13 12 43
> 
> ```
>   File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 49, in render
>     data = render_page_by_language(path)
>   File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
>     return render_page(path)
>   File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 194, in render_page
>     return build(path)
>   File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 201, in build
>     return build_page(path)
>   File "/home/diamo/Frappe/apps/frappe/frappe/website/render.py", line 224, in build_page
>     html = frappe.get_template(context.template).render(context)
>   File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
>     self.environment.handle_exception()
>   File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
>     reraise(*rewrite_traceback_stack(source=source))
>   File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
>     raise value.with_traceback(tb)
>   File "/home/diamo/Frappe/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 1, in top-level template code
>     {% extends "wiki/doctype/wiki_page/templates/wiki_doc.html" %}
>   File "/home/diamo/Frappe/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_doc.html", line 2, in top-level template code
>     {%- from "templates/includes/navbar/navbar_items.html" import render_item -%}
>   File "/home/diamo/Frappe/apps/frappe/frappe/./templates/base.html", line 41, in top-level template code
>     {%- block head_include %}
>   File "/home/diamo/Frappe/apps/wiki/wiki/./wiki/doctype/wiki_page/templates/wiki_page.html", line 9, in block "head_include"
>     {{ include_style('wiki.bundle.css') }}
>   File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 460, in call
>     if not __self.is_safe_callable(__obj):
>   File "/home/diamo/Frappe/env/lib/python3.8/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
>     getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
> jinja2.exceptions.UndefinedError: 'include_style' is undefined```
> ```

@federicocalvo 
I think you might need to upgrade your node to 14 and frappe also to the latest version
then do bench setup requirements and bench build

**Comment by zuron7** [comment]
Just tested this out on a local branch. Amazing job on this. Can handle our company knowledge base on ERPNext itself now. Thank you!

**Pull request merged**
