### PR TITLE
fixed left sidebar returning undefined

### PR DESCRIPTION
**Pull request by NoBoneZ**
Whenever a page sidebar instance is created for on a wiki page, it returns undefined as the name, i have been able to fix that

### CODE REVIEW

**Comment by BreadGenie** [comment]
Hi @NoBoneZ can you explain how to reproduce this bug?

I tried adding a `Page` and `Group` item to the sidebar but wasn't able to reproduce it.

**Comment by NoBoneZ** [comment]
Hello, sorry for the late response,  you will need to create a wiki page,
with published on check, after which, you will view it on website, while
viewing on website, you will scroll down to the bottom and click on edit
page, after that,on the left sidebar, you will see a add to sidebar icon,
you will click it, then, in the first field on the form, pick page, select
the wiki page and then, save it......That was how i produced the bug......

**Comment by NoBoneZ** [comment]
> Hi @NoBoneZ can you explain how to reproduce this bug?
> 
> I tried adding a `Page` and `Group` item to the sidebar but wasn't able to reproduce it.
> 
> Edit: Was able to reproduce it for `Page` by choosing a page from side bar (was trying to do the same from the bottom link near `Edit Page`)

Yes yes, from choosing page from the sidebar

**Comment by BreadGenie** [comment]
Sorry for getting back to you late. We have decided to allow creation of a new `Page` only from below the wiki page and has removed the option to add `Page` from the sidebar in 5448346c35f13b51fad4de0b1cd9b2fdac465842. 

There were couple issues with adding a page from the sidebar
- Returning the name as `undefined`.
- Creating a `Group` instead of a `Page`.

Thanks a lot for the PR but unfortunately this has to be closed.

**Pull request closed without merging**
